### ISSUE TITLE
Bubble not appearing

### ISSUE THREAD

**Issue by myinnos** [L4Digital/FastScroll#9] opened 2017-01-08 10:13 UTC
Scroll view works well as name said fast scroller, but bubble view is not showing at all on scroll!

```
 @Override
    public String getSectionText(int position) {
        return "some text";
    }
```

**Comment by randr0id** [comment] 2017-01-09 22:23
If the bubble doesn't show at all it's most likely that the adapter implementing the `FastScroller.SectionIndexer` wasn't setup correctly. Can you post snippets from your xml layout and where you are setting the adapter to the FastScrollRecyclerView?

**Comment by myinnos** [comment] 2017-01-10 04:52
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <include android:id="@+id/standard_toolbar" layout="@layout/standard_toolbar" />

 <com.l4digital.fastscroll.FastScrollRecyclerView
        android:id="@+id/recyclerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@id/standard_toolbar"
        app:bubbleColor="#00bb00"
        app:bubbleTextColor="#ffffff"
        app:handleColor="#999999"
        app:trackColor="#bbbbbb"
        app:hideScrollbar="false"
        app:showTrack="false" />

</RelativeLayout >

```

**Comment by randr0id** [comment] 2017-01-10 18:24
I used your layout for the example project and the bubble appeared correctly (attached screenshot). Take a look at how the example project implements FastScroll to see if there are any differences with your implementation.

<img src="https://cloud.githubusercontent.com/assets/8051257/21818991/b6d035b0-d71e-11e6-9295-eb6625d3fb9b.png" alt="screenshot" width="270">

**Comment by myinnos** [comment] 2017-01-11 05:21
**Base Activity**

```
@BindView(R.id.recycler_view)
    FastScrollRecyclerView recyclerView;

       recyclerView.setHasFixedSize(true);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        recyclerView.setAdapter(new UserAppsAdapter(getAppsList(), recyclerView));
```

**Adapter class**

`public class UserAppsAdapter extends RecyclerView.Adapter<UserAppsAdapter.ViewHolder> implements FastScroller.SectionIndexer {`

```
 @Override
    public String getSectionText(int position) {
        return "test";
    }
```

Let me know if any thing missed out!

**Comment by randr0id** [comment] 2017-01-11 21:33
I don't see any issues with this code, except for passing the recyclerView into the adapter constructor seems unnecessary.

When scrolling, are you seeing the scrollbar handle? If so, when touching the handle to fastscroll the bubble should appear.

**Comment by myinnos** [comment] 2017-01-12 04:40
Your awesome, exactly as you said, the bubble is appearing when i touching the handle. 

Then how  can i resolve now!

**Comment by randr0id** [comment] 2017-01-12 04:58
Great! I'll close this issue.

**Closed by randr0id** 2017-01-12 04:58 UTC

**Comment by myinnos** [comment] 2017-01-12 05:47
How you closed this issue! still need to resolved

**Comment by randr0id** [comment] 2017-01-12 05:52
Your last comment said the bubble was now appearing, which resolves the original issue. This is the intended behavior.

**Comment by myinnos** [comment] 2017-01-12 05:55
I Have Question ? Is bubble will show only when user touch on scroll ? if yes my issue resolved 👍

or Even when user scroll view if bubble appears ?

**Comment by randr0id** [comment] 2017-01-12 05:57
Yes, the bubble only appears when the user touches the scroll handle as intended.

**Comment by myinnos** [comment] 2017-01-12 06:01
Thanks! 🥇 awesome 💯! My issue resolved 👍

**Comment by karthickperumal** [comment] 2017-05-03 11:30
@randr0id 
Hi I am getting Java.lang.StringIndexOutOfBoundsException: length=0; index=0 error on scrolling.Kindly give me the solution.

**Comment by randr0id** [comment] 2017-05-03 17:00
@karthickperumal I need more context or a stacktrace. From the error you provided it looks like your trying to access a character by index on an empty String, and I don't think there is code that does that in the library (there is in the example).
